// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLXM7D-FMVEu1WYvbx0Su-4qfSCKKhn88',
    appId: '1:12455198823:web:33faf6718eb0f5e12254c2',
    messagingSenderId: '12455198823',
    projectId: 'henshin-197b5',
    authDomain: 'henshin-197b5.firebaseapp.com',
    storageBucket: 'henshin-197b5.appspot.com',
    measurementId: 'G-WPEDT820EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfKAs3vKn7vDG6PAURFfqwp_C1Bs02DY8',
    appId: '1:12455198823:android:76377d896179dcd72254c2',
    messagingSenderId: '12455198823',
    projectId: 'henshin-197b5',
    storageBucket: 'henshin-197b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA96yS-4lAF00jwCGIXxoQkVd9SbUUvH2w',
    appId: '1:12455198823:ios:4dd58259ba1f53e82254c2',
    messagingSenderId: '12455198823',
    projectId: 'henshin-197b5',
    storageBucket: 'henshin-197b5.appspot.com',
    iosClientId: '12455198823-b3i0k44lqq349fqflb3tb2di9pvt6sql.apps.googleusercontent.com',
    iosBundleId: 'com.example.henshin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA96yS-4lAF00jwCGIXxoQkVd9SbUUvH2w',
    appId: '1:12455198823:ios:4dd58259ba1f53e82254c2',
    messagingSenderId: '12455198823',
    projectId: 'henshin-197b5',
    storageBucket: 'henshin-197b5.appspot.com',
    iosClientId: '12455198823-b3i0k44lqq349fqflb3tb2di9pvt6sql.apps.googleusercontent.com',
    iosBundleId: 'com.example.henshin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLXM7D-FMVEu1WYvbx0Su-4qfSCKKhn88',
    appId: '1:12455198823:web:47aad20fb07e25182254c2',
    messagingSenderId: '12455198823',
    projectId: 'henshin-197b5',
    authDomain: 'henshin-197b5.firebaseapp.com',
    storageBucket: 'henshin-197b5.appspot.com',
    measurementId: 'G-SP4N5J2QPT',
  );
}
